### ISSUE TITLE
Feature request: graceful restart after adding/removing a new domain

### ISSUE THREAD

**Issue by codewinch** [caddyserver/certmagic#182]
## What would you like to have changed?

I'd love to be able to add/remove domains (for example, [generic-s3](https://github.com/thomersch/certmagic-generic-s3/blob/master/example/example.go)) and gracefully restart HTTPS (for example, with *[endless](https://github.com/fvbock/endless)*)

## Why is this feature a useful, necessary, and/or important addition to this project?

This would make it possible to easily serve TLS for a large, *dynamic* list of domains, especially across a cluster, rather than a static list that requires a full server restart and dropped connections (as of now?). This could even take advantage of a separate goroutine that monitors an external list of domains and then triggers a server reconfiguration.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

It looks like caddy might be able to do this with SIGUSR1, but I'd like to be able to do this internally to my server.

**Comment by francislavoie** [comment]
Caddy doesn't support `SIGUSR1`. Instead reloads are triggered with the [`caddy reload` command](https://caddyserver.com/docs/command-line#caddy-reload) to push a new config, or by using Caddy's [config API](https://caddyserver.com/docs/api) which implicitly triggers graceful reloads by virtue of doing an in-memory config swap.

There's nothing in Certmagic that prevents you from doing this yourself in your own app. See the [Advanced Use](https://github.com/caddyserver/certmagic#advanced-use) section of the README that outlines the "long-way" of setting up certmagic with your own `http.Server`.

Also, you could consider using [On-Demand TLS](https://github.com/caddyserver/certmagic#on-demand-tls) instead which would let you avoid needing to reload anything, since cert issuance would be done on-the-fly.

**Comment by codewinch** [comment]
Thank you @francislavoie ! We'll look around for some example code and try both ideas out, especially the `DecisionFunc`!
