### ISSUE TITLE
Windows test taking significantly longer time than macos/ ubuntu

### ISSUE THREAD

**Issue by wusatosi** [caddyserver/certmagic#228]
Currently, in CI testing. 
The windows testing pipeline takes the majority amount of time.
![image](https://user-images.githubusercontent.com/26424577/232266091-1b856b42-a26a-4d7e-9e4b-60e260ef4bac.png)

According to the log.
Looks like `TestFindZoneByFqdn` is spending 160s on [windows](https://github.com/caddyserver/certmagic/actions/runs/4670033562/jobs/8269270484#step:7:82).
![image](https://user-images.githubusercontent.com/26424577/232266214-089468e2-3a59-45aa-bd0b-44de5a23f826.png)

While the same test spends under a second on [Ubuntu](https://github.com/caddyserver/certmagic/actions/runs/4670033562/jobs/8269270198#step:7:82)/ [Macos](https://github.com/caddyserver/certmagic/actions/runs/4670033562/jobs/8269270344#step:7:82).

![image](https://user-images.githubusercontent.com/26424577/232266240-77187c3d-3a37-470d-8e8d-3f4f8c720958.png)

Relevant code here:
https://github.com/caddyserver/certmagic/blob/462f5e2334a762adc04d2e9ca6200239ffb49a5c/dnsutil_test.go#L87-L177

**Comment by francislavoie** [comment]
Hmm. I guess we should set a more aggressive dial timeout for the nameservers? The timeout is hardcoded to 10s. Seems like it's taking almost the maximum amount of time in there. https://github.com/caddyserver/certmagic/blob/462f5e2334a762adc04d2e9ca6200239ffb49a5c/dnsutil.go#L145

I wonder what's different about the Windows stack that makes it not fail-fast.

**Comment by wusatosi** [comment]
I am not familiar with this, but this does not seem to be an timeout issue, as ubuntu & macos both finish this set of tests in under a second.

**Comment by francislavoie** [comment]
I'm pretty sure it is because Windows doesn't fail early, and it waits until the timeout.

Doing the math on the tests, notice that there's two DNS servers that don't exist for the first test, and `sendDNSQuery` tries first with TCP, then again with UDP. So that's 4 attempts sequentially, 4 * 10s, ~40s.

For the next test, there's 3, twice, so 6 * 10s. But it takes 100s, I'm not sure how to explain the rest of the time spent but there might be some other queries being performed along the way.

**Comment by wusatosi** [comment]
Sorry I am really not familiar with the HAHA. If you look closely at the time spent on each test, `several_non_existent_nameservers` and `only_non_existent_nameservers` takes the overwhelmingly majority of time. This seem to only trigger when the name server is "non existent".

https://github.com/caddyserver/certmagic/blob/462f5e2334a762adc04d2e9ca6200239ffb49a5c/dnsutil_test.go#L130-L142

Looking at the addresses, my hypothesis will be that for macos and ubuntu, accessing ports that's not open on loop back will immediately cause an error (ex. not reachable), while windows just holds the process until it timeouts. In that case, yes reducing timeout will definitely help.

**Comment by francislavoie** [comment]
I tried running this on my Windows machine. As-is, this is the runtime:

```
    --- PASS: TestFindZoneByFqdn/several_non_existent_nameservers (48.15s)
    --- PASS: TestFindZoneByFqdn/only_non_existent_nameservers (108.21s)
```

Reducing the `dnsTimeout` from 10s to 1s produces:

```
    --- PASS: TestFindZoneByFqdn/several_non_existent_nameservers (8.13s)
    --- PASS: TestFindZoneByFqdn/only_non_existent_nameservers (18.13s)
```

So it helps, but it's not a complete solution. And it might cause bad behaviour in cases where the network is legitimately slow to respond instead of failing to connect.

We might be using `miekg/dns` incorrectly as well, there might be some flag we should be setting for it to behave better on Windows. I dunno.

**Comment by francislavoie** [comment]
Decided to turn off the tests: https://github.com/caddyserver/certmagic/pull/229
