### ISSUE TITLE
Gandi dns-01 challenge fail: 400 Absolute rrset_name must end with mydomain.org

### ISSUE THREAD

**Issue by onny** [caddyserver/certmagic#260]
## What version of the package are you using?
v0.17.2

## What are you trying to do?
Certmagic is used in mail server Maddy to retrieve certificates using dns-01 challenge

## What steps did you take?
Configured Maddy with following parameters:
```
tls {
  loader acme {
    email onny@project-insanity.org
    agreed
    hostname mx1.example.org
    challenge dns-01
    dns gandi {
      api_token "{env:GANDI_API_KEY}"
    }
  }
}
```

## What did you expect to happen, and what actually happened instead?
Generating certificates worked before ~August this year 2023. Then there was some regression without updating Maddy. The error message is: `could not get certificate from issuer        {"error":"[example.org] solving challenges: presenting for challenge: adding temporary record for zone \"example.org.\": LiveDNS returned a 400 (Absolute rrset_name must end with example.org. (_acme-challenge.)`

## How do you think this should be fixed?
It's possible that this bug is also present in latest versions of certmagic. I'm happy to help out testing that if requested. Maybe there was some API change which resulted in this error

## Please link to any related issues, pull requests, and/or discussion
Downstream issue in Maddy mail server https://github.com/foxcpp/maddy/issues/619

**Comment by mholt** [comment]
Sorry for my late reply. Maddy's a neat project.

That actually looks like a bug in the gandi libdns library: https://github.com/libdns/gandi

All CertMagic does is give the provider the domain name and the record value, then it's up to the libdns provider to do the work. And since I didn't develop the gandi plugin (nor am I a customer of gandi) I'm afraid I can't help you much with that...

But I am happy to help work with you and them to find a resolution where I can be helpful!

Closing, but if this turns out to be a bug in CertMagic I can definitely reopen it.
