### ISSUE TITLE
Does certmagic have any limitations?

### ISSUE THREAD

**Issue by gitmko0** [caddyserver/certmagic#80]
e.g. 50 certs per hour limit or something with letsencrypt?
i'm running web hosting services and will be hosting ... (hopefully) millions of domain names.

will there be any issues per server of deployment etc?

**Comment by mholt** [comment]
> Does certmagic have any limitations?

No... it does not. 😈 

![hokMyu1PAKfJK](https://user-images.githubusercontent.com/1128849/89697589-0feecd80-d8da-11ea-8e71-d863ec7250b1.gif)

---

Actual answer:

It does have some internal throttling that makes it a good citizen of the Internet, i.e. a well-behaved ACME client:

https://github.com/caddyserver/certmagic/blob/5fd26543e052a4cfc7978ee166b74305227f9eb9/acmeclient.go#L293-L333

As the comment explains, we do not attempt to replicate the LE rate limits because we do not share their CA's internal state. We can only do our best to not hammer their endpoint, and to backoff and retry when we start hitting their rate limits:

https://github.com/caddyserver/certmagic/blob/5fd26543e052a4cfc7978ee166b74305227f9eb9/async.go#L158-L187

> i'm running web hosting services and will be hosting ... (hopefully) millions of domain names.

CertMagic is suitable for millions of certificates. You'll need a machine that can handle it; that's a lot of cryptography and encoding/decoding cycles.
