### ISSUE TITLE
Add Config.Unmanage

### ISSUE THREAD

**Issue by emersion** [caddyserver/certmagic#92]
## What would you like to have changed?

I'd like to add a way to stop managing a certificate.

## Why is this feature a useful, necessary, and/or important addition to this project?

Right now there's only a way to add a domain name to the list of managed certificates. This means the number of managed certificates can only grow.

When a certificate is no longer to be used, I'd like to communicate that information to certmagic so that it stops renewing the certificate.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Workaround: throw away the whole `Config` and re-add all domain names I want certmagic to manage. In the meantime, I just let certmagic manage unused certificates.

**Comment by emersion** [comment]
Hm, I just noticed there is a `context.Context` you can provide to `ManageAsync`. 

> Cancelling ctx will cancel retries and shut down any goroutines spawned by ManageAsync. 

Does that mean cancelling `ctx` will stop renewals and eventually evict the cert from the cache?

**Comment by mholt** [comment]
Good questions!

I admit this is not super clear, especially right now pre-1.0. `ManageAsync()` loads a cert into the in-memory cache -- or if it does not yet exist in storage, it will obtain it -- so that it can be used. That's all it does by itself: the rest is up to the in-memory cache. The cache lifetime is different from that of configs (on which you call `ManageAsync()`) because a config might only live for a brief moment, whereas the cache could be needed for days and weeks and even years. The initial loading or obtaining of the certificate is bound to ctx, but not the whole cache. While a cache is active (`NewCache()`), it maintains the certificates that are in it. This maintenance can be stopped by calling `Stop()`; it is not bound by ctx.

So, to clarify, throwing away configs is fine: they can be ephemeral. But the cache should be singular (for most applications) and long-lived.

Right now there is no exported way to remove a certificate from the cache, only an unexported method:

https://github.com/caddyserver/certmagic/blob/3cc8865d3cd480e50a7f3f0e929a2fa78c55351e/cache.go#L228-L232

We could export it, but what do you want your input to be: just a domain name? It gets complicated because a domain could appear on more than 1 certificate. The cache contains both managed and unmanaged certificates. Do you want to only be able to remove managed certificates, then? Or unmanaged (manually-loaded and manually-renewed) certs too?

**Comment by emersion** [comment]
>The initial loading or obtaining of the certificate is bound to ctx, but not the whole cache.

Okay, that makes it clear that cancelling the context won't be enough.

> But the cache should be singular (for most applications) and long-lived.

Makes sense to me.

> Right now there is no exported way to remove a certificate from the cache, only an unexported method

Nice!

>what do you want your input to be: just a domain name?

Since `Manage` takes domain names, I think it would make sense to have a function that takes a domain name. Of course if a certificate contains multiple domain names, it should not be evicted, but I'd expect the maintenance routine to request a fresh certificate without the removed domain name when the certificate expires (well, before it expires).

All of this is getting pretty complicated. Maybe it would be better to let users handle it if they need to. But how does certmagic handle `Manage` when multiple domain names are supplied? Does it always request a single cert with all of the domain names supplied? Does it always request as many certificates as there are domain names?

If certmagic batches domain names for certificate requests, a function taking a `Certificate` would be annoying for users.

>Do you want to only be able to remove managed certificates, then? Or unmanaged (manually-loaded and manually-renewed) certs too?

I can definitely see a use-case for removing unmanaged certificates from the cache:

- Create a Caddy config with an unmanaged certificate
- Start Caddy
- Remove the unmanaged certificate from the config
- Reload Caddy

I wouldn't want Caddy to use the old certificate "by mistake" (e.g. client connecting with SNI and getting the old cert).

**Comment by mholt** [comment]
> All of this is getting pretty complicated.

You can see why I haven't implemented this yet. :joy:

> But how does certmagic handle Manage when multiple domain names are supplied?

All of the certificates that CertMagic manages are single-SAN certificates. As you can begin to see, this already drastically reduces complexity. Since `Manage()` adds only _managed_ (automated) certificates to the cache, it's easy in that each domain name maps to its own certificate.

> Does it always request as many certificates as there are domain names?

So, yes to this one.

Your original request is for a `Cofig.Unmanage()` method. I suppose, if this specifically removes _managed_ certificates only from the cache, then it should be just fine to remove them, since we can guarantee that there's only one name per certificate. We cannot make that guarantee for unmanaged (user-added, manually-renewed) certificates.

I am also not 100% sure if the 1:1 mapping of domain-to-certificate is a documented, exported API guarantee: i.e. I'd need to double-check whether it is an implementation detail or something that users rely on. I know there are parts of CertMagic that do not work for auto-maintenance if there is more than 1 domain name on the certificate (for example, we store certificates keyed by _the domain name_, not capable of keying them by more than one domain). I know that 1:1 is best practice and I have no intention of diverting from that, but before making possibly permanent design decisions I'd need to be sure.

> I can definitely see a use-case for removing unmanaged certificates from the cache:

This might be harder. Or not, if we "just" export the `removeCertificate()` method:

https://github.com/caddyserver/certmagic/blob/d45c5b1633f93fad35d4c806aac844debb887bd9/cache.go#L228-L250

You'll notice that this function requires a lock on an unexported value, so we'd have to make a new wrapper method, of course. But this also means the user will have to get the Certificate value. We'd have to figure out what the API would look like.

**Comment by emersion** [comment]
>Your original request is for a Cofig.Unmanage() method. I suppose, if this specifically removes managed certificates only from the cache, then it should be just fine to remove them, since we can guarantee that there's only one name per certificate. We cannot make that guarantee for unmanaged (user-added, manually-renewed) certificates.

OK, that makes perfect sense. Yes, `Config.Unmanage` would be enough for my use-case.

>Or not, if we "just" export the removeCertificate() method:

I think that's worthwhile too, and maybe orthogonal to `Config.Unmanage`.

>But this also means the user will have to get the Certificate value. We'd have to figure out what the API would look like.

We already have `Cache.AllMatchingCertificates`, this would be enough for simple use-cases I think. For anything more complicated maybe we can add a method that takes a `tls.Certificate` and returns a `certmagic.Certificate`. Or something like that.
